import { motion } from "motion/react";
import {
  BookOpen,
  Check,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Gauge,
  Globe,
  Printer,
  RefreshCw,
  ShieldAlert,
  ShieldCheck,
} from "lucide-react";
import { useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Citation, ReportResult, TraceEntry } from "../api";
import { AGENT_BY_KEY, AGENTS, formatDuration, isAgentKey } from "../lib/agents";
import { useToast } from "./Toast";

// The Writer is told one source_id per bracket, but a model occasionally packs
// several into one anyway (`[rag:a#0, web:1]`) - split those into one chip
// each rather than rendering the whole unmatched bracket as plain text.
const CITE_RE = /\[([A-Za-z0-9_:.#/-]+(?:\s*,\s*[A-Za-z0-9_:.#/-]+)*)\](?!\()/g;

function linkifyCitations(report: string): string {
  return report.replace(CITE_RE, (_match, group: string) =>
    group
      .split(",")
      .map((id) => id.trim())
      .map((id) => `[[${id}]](#cite-${encodeURIComponent(id)})`)
      .join(""),
  );
}

function toMarkdownExport(result: ReportResult): string {
  const lines = [`# ${result.question}`, "", result.report ?? "", ""];
  if (result.citations.length) {
    lines.push("## Sources", "");
    for (const c of result.citations) {
      lines.push(c.type === "web" ? `- **[${c.source_id}]** ${c.title || c.url} — ${c.url}` : `- **[${c.source_id}]** ${c.file}${c.chunk_index !== undefined ? ` (chunk ${c.chunk_index})` : ""}`);
    }
    lines.push("");
  }
  lines.push(`_Generated by AgentDesk · ${result.status === "passed" ? "verified by the Critic" : "not fully verified"}_`);
  return lines.join("\n");
}

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "report";
}

type Tab = "report" | "sources" | "timeline" | "critic";

export default function ReportView({ result, trace, onRerun }: { result: ReportResult; trace: TraceEntry[]; onRerun: () => void }) {
  const [tab, setTab] = useState<Tab>("report");
  const [highlighted, setHighlighted] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const toast = useToast();
  const linkified = useMemo(() => linkifyCitations(result.report ?? ""), [result.report]);
  const citationById = useMemo(() => new Map(result.citations.map((c) => [c.source_id, c])), [result.citations]);
  const passed = result.status === "passed";
  const flagged = result.critic.unsupported_claims ?? [];
  const words = useMemo(() => (result.report ?? "").split(/\s+/).filter(Boolean).length, [result.report]);

  function jumpToCitation(id: string) {
    setTab("sources");
    setHighlighted(id);
    window.setTimeout(() => document.getElementById(`cite-${id}`)?.scrollIntoView({ behavior: "smooth", block: "center" }), 60);
    window.setTimeout(() => setHighlighted((cur) => (cur === id ? null : cur)), 2000);
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(toMarkdownExport(result));
      setCopied(true);
      toast("Report copied as Markdown");
      window.setTimeout(() => setCopied(false), 1500);
    } catch {
      toast("Clipboard is blocked in this browser", "error");
    }
  }

  function download() {
    const blob = new Blob([toMarkdownExport(result)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${slugify(result.question)}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast("Downloaded Markdown file");
  }

  const tabs: { key: Tab; label: string; count?: number; icon: typeof FileText }[] = [
    { key: "report", label: "Report", icon: FileText },
    { key: "sources", label: "Sources", count: result.citations.length, icon: BookOpen },
    { key: "timeline", label: "Timeline", icon: Gauge },
    { key: "critic", label: "Critic", count: flagged.length || undefined, icon: passed ? ShieldCheck : ShieldAlert },
  ];

  return (
    <div className="animate-fade-up flex flex-col gap-4">
      {/* Verdict banner */}
      <div
        className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border px-4 py-3"
        style={{
          borderColor: passed ? "#34d39940" : "#fbbf2440",
          background: passed ? "linear-gradient(90deg,#34d39914,transparent)" : "linear-gradient(90deg,#fbbf2414,transparent)",
        }}
      >
        <div className="flex items-center gap-2.5">
          {passed ? <ShieldCheck size={18} className="text-[var(--ok)]" /> : <ShieldAlert size={18} className="text-[var(--warn)]" />}
          <div>
            <div className="text-sm font-semibold">{passed ? "Verified by the Critic" : "Delivered without full verification"}</div>
            <div className="text-[11.5px] text-[var(--text-dim)]">
              {passed ? "Every claim was checked against the retrieved evidence." : "The revision limit was reached. Check the flagged claims in the Critic tab."}
            </div>
          </div>
        </div>
        <div className="flex gap-2">
          <Stat label="revisions" value={result.revisions} />
          <Stat label="research rounds" value={result.research_rounds} />
          <Stat label="sources" value={result.citations.length} />
          <Stat label="words" value={words} />
        </div>
      </div>

      <div className="glass print-root rounded-2xl">
        {/* Tabs + actions */}
        <div className="no-print flex flex-wrap items-center justify-between gap-2 border-b border-[var(--border)] px-2 py-1.5">
          <div role="tablist" className="flex gap-0.5 overflow-x-auto">
            {tabs.map((t) => (
              <button
                key={t.key}
                role="tab"
                aria-selected={tab === t.key}
                onClick={() => setTab(t.key)}
                className={`relative flex items-center gap-1.5 whitespace-nowrap rounded-lg px-3 py-2 text-[12.5px] font-medium transition ${
                  tab === t.key ? "text-[var(--text)]" : "text-[var(--text-faint)] hover:text-[var(--text-dim)]"
                }`}
              >
                {tab === t.key && (
                  <motion.span layoutId="report-tab" className="absolute inset-0 rounded-lg bg-white/[0.06]" transition={{ type: "spring", duration: 0.35, bounce: 0.15 }} />
                )}
                <t.icon size={13} className="relative" />
                <span className="relative">{t.label}</span>
                {t.count !== undefined && <span className="relative rounded-full bg-white/[0.07] px-1.5 text-[10px]">{t.count}</span>}
              </button>
            ))}
          </div>
          <div className="flex gap-0.5">
            <IconButton label={copied ? "Copied" : "Copy as Markdown"} onClick={copy}>
              {copied ? <Check size={14} className="text-[var(--ok)]" /> : <Copy size={14} />}
            </IconButton>
            <IconButton label="Download .md" onClick={download}>
              <Download size={14} />
            </IconButton>
            <IconButton
              label="Print / save as PDF"
              onClick={() => {
                setTab("report");
                window.setTimeout(() => window.print(), 80);
              }}
            >
              <Printer size={14} />
            </IconButton>
            <IconButton label="Ask again" onClick={onRerun}>
              <RefreshCw size={14} />
            </IconButton>
          </div>
        </div>

        <div key={tab} className="animate-fade-up">
            {tab === "report" && (
              <article className="report-md px-5 py-5 text-[14.5px] leading-[1.75] sm:px-7 sm:py-6">
                <h1 className="!mt-0 hidden print:block">{result.question}</h1>
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    a: ({ href, children }) => {
                      if (href?.startsWith("#cite-")) {
                        const id = decodeURIComponent(href.slice(6));
                        return <CitationChip id={id} citation={citationById.get(id)} onJump={jumpToCitation} />;
                      }
                      return (
                        <a href={href} target="_blank" rel="noreferrer" className="text-[var(--accent-strong)] underline decoration-[var(--accent)]/40 underline-offset-2">
                          {children}
                        </a>
                      );
                    },
                  }}
                >
                  {linkified}
                </ReactMarkdown>
              </article>
            )}
            {tab === "sources" && <SourcesTab citations={result.citations} highlighted={highlighted} />}
            {tab === "timeline" && <TimelineTab trace={trace} />}
            {tab === "critic" && <CriticTab result={result} />}
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl bg-white/[0.03] px-2.5 py-1 text-center">
      <div className="font-mono text-[13px] font-semibold leading-tight">{value}</div>
      <div className="text-[9.5px] uppercase tracking-wide text-[var(--text-faint)]">{label}</div>
    </div>
  );
}

function IconButton({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) {
  return (
    <button
      onClick={onClick}
      aria-label={label}
      title={label}
      className="flex h-8 w-8 items-center justify-center rounded-lg text-[var(--text-dim)] transition hover:bg-white/[0.06] hover:text-[var(--text)]"
    >
      {children}
    </button>
  );
}

function CitationChip({ id, citation, onJump }: { id: string; citation?: Citation; onJump: (id: string) => void }) {
  const known = !!citation;
  const isWeb = citation?.type === "web";
  return (
    <span className="group relative inline-block align-baseline">
      <button
        type="button"
        onClick={() => known && onJump(id)}
        className="mx-0.5 inline-flex -translate-y-px items-center gap-1 rounded-md border px-1.5 py-px font-mono text-[10.5px] font-medium no-underline transition hover:brightness-125"
        style={{
          borderColor: known ? (isWeb ? "#34d39966" : "#7c6dfa88") : "var(--border)",
          background: known ? (isWeb ? "#34d3991a" : "var(--accent-soft)") : "transparent",
          color: known ? (isWeb ? "var(--ok)" : "var(--accent-strong)") : "var(--text-faint)",
        }}
      >
        {isWeb ? <Globe size={9} /> : <BookOpen size={9} />}
        {id}
      </button>
      {known && (
        <span className="pointer-events-none absolute bottom-full left-1/2 z-20 mb-1.5 hidden w-64 max-w-[70vw] -translate-x-1/2 rounded-xl border border-[var(--border-strong)] bg-[#0d0f17f2] p-2.5 text-left text-[11.5px] leading-snug shadow-2xl backdrop-blur-md group-hover:block">
          <span className="block font-mono text-[10px] text-[var(--text-faint)]">{isWeb ? "Web source" : "Knowledge base"}</span>
          <span className="mt-0.5 block font-medium text-[var(--text)]">{isWeb ? citation.title || citation.url : citation.file}</span>
          {!isWeb && citation.chunk_index !== undefined && <span className="block text-[var(--text-dim)]">chunk {citation.chunk_index}</span>}
          {citation.score !== undefined && <span className="block text-[var(--text-dim)]">relevance {citation.score.toFixed(2)}</span>}
          <span className="mt-1 block text-[10px] text-[var(--accent-strong)]">Click to open in Sources</span>
        </span>
      )}
    </span>
  );
}

function SourcesTab({ citations, highlighted }: { citations: Citation[]; highlighted: string | null }) {
  const [filter, setFilter] = useState<"all" | "rag" | "web">("all");
  const counts = { all: citations.length, rag: citations.filter((c) => c.type !== "web").length, web: citations.filter((c) => c.type === "web").length };
  const shown = citations.filter((c) => filter === "all" || (filter === "web" ? c.type === "web" : c.type !== "web"));

  if (citations.length === 0) {
    return <Empty text="The report didn't cite any sources." />;
  }

  return (
    <div className="flex flex-col gap-3 p-4">
      <div className="flex gap-1.5">
        {(["all", "rag", "web"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`rounded-full border px-2.5 py-1 text-[11px] font-medium transition ${
              filter === f ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--text)]" : "border-[var(--border)] text-[var(--text-dim)] hover:text-[var(--text)]"
            }`}
          >
            {f === "all" ? "All" : f === "rag" ? "Knowledge base" : "Web"} · {counts[f]}
          </button>
        ))}
      </div>
      <div className="grid gap-2 sm:grid-cols-2">
        {shown.map((c) => {
          const isWeb = c.type === "web";
          const hl = highlighted === c.source_id;
          return (
            <div
              key={c.source_id}
              id={`cite-${c.source_id}`}
              className="flex items-start gap-3 rounded-xl border px-3.5 py-3 transition-all duration-300"
              style={{
                borderColor: hl ? "var(--accent)" : "var(--border)",
                background: hl ? "var(--accent-soft)" : "rgba(255,255,255,0.02)",
                transform: hl ? "scale(1.02)" : undefined,
              }}
            >
              <span
                className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg"
                style={{ background: isWeb ? "#34d3991f" : "#7c6dfa24", color: isWeb ? "var(--ok)" : "var(--accent-strong)" }}
              >
                {isWeb ? <Globe size={13} /> : <BookOpen size={13} />}
              </span>
              <div className="min-w-0 flex-1">
                <div className="truncate font-mono text-[10.5px] text-[var(--text-faint)]">{c.source_id}</div>
                {isWeb ? (
                  <a href={c.url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-[13px] text-[var(--accent-strong)] hover:underline">
                    <span className="truncate">{c.title || c.url}</span>
                    <ExternalLink size={11} className="shrink-0" />
                  </a>
                ) : (
                  <div className="truncate text-[13px]">
                    {c.file}
                    {c.chunk_index !== undefined && <span className="text-[var(--text-faint)]"> · chunk {c.chunk_index}</span>}
                  </div>
                )}
                {c.score !== undefined && (
                  <div className="mt-1.5 flex items-center gap-2">
                    <div className="h-1 flex-1 overflow-hidden rounded-full bg-white/[0.06]">
                      <div className="h-full rounded-full bg-gradient-to-r from-[#7c6dfa] to-[#38bdf8]" style={{ width: `${Math.max(4, Math.min(1, c.score) * 100)}%` }} />
                    </div>
                    <span className="font-mono text-[10px] text-[var(--text-faint)]">{c.score.toFixed(2)}</span>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TimelineTab({ trace }: { trace: TraceEntry[] }) {
  if (trace.length === 0) return <Empty text="No timing data for this run." />;
  const total = trace.reduce((s, e) => s + e.elapsed_ms, 0) || 1;
  const bars = trace.map((e, i) => ({ ...e, start: trace.slice(0, i).reduce((s, x) => s + x.elapsed_ms, 0) }));
  const perAgent = AGENTS.map((a) => ({
    agent: a,
    ms: trace.filter((e) => e.node === a.key).reduce((s, e) => s + e.elapsed_ms, 0),
  })).filter((x) => x.ms > 0);
  const slowest = Math.max(...perAgent.map((x) => x.ms), 1);

  return (
    <div className="flex flex-col gap-6 p-4 sm:p-5">
      <div>
        <div className="mb-3 flex items-baseline justify-between">
          <h3 className="text-[13px] font-semibold">Execution timeline</h3>
          <span className="font-mono text-[11px] text-[var(--text-faint)]">total {formatDuration(total)}</span>
        </div>
        <div className="flex flex-col gap-1.5">
          {bars.map((b, i) => {
            const meta = isAgentKey(b.node) ? AGENT_BY_KEY[b.node] : null;
            const color = meta?.color ?? "#7c6dfa";
            return (
              <div key={i} className="group flex items-center gap-3">
                <span className="w-20 shrink-0 truncate text-right text-[11px] font-medium" style={{ color }}>
                  {meta?.label ?? b.node}
                </span>
                <div className="relative h-5 flex-1 rounded-md bg-white/[0.03]">
                  <div
                    className="grow-x absolute top-0 h-full rounded-md"
                    style={{
                      animationDelay: `${i * 50}ms`,
                      left: `${(b.start / total) * 100}%`,
                      width: `max(3px, ${(b.elapsed_ms / total) * 100}%)`,
                      background: `linear-gradient(90deg, ${color}, ${color}aa)`,
                      boxShadow: `0 0 16px -4px ${color}`,
                    }}
                  />
                  <div className="pointer-events-none absolute -top-8 left-1/2 z-10 hidden -translate-x-1/2 whitespace-nowrap rounded-lg border border-[var(--border-strong)] bg-[#0d0f17] px-2 py-1 text-[10.5px] text-[var(--text-dim)] group-hover:block">
                    {b.detail || b.node}
                  </div>
                </div>
                <span className="w-14 shrink-0 font-mono text-[10.5px] text-[var(--text-faint)]">{formatDuration(b.elapsed_ms)}</span>
              </div>
            );
          })}
        </div>
      </div>

      <div>
        <h3 className="mb-3 text-[13px] font-semibold">Time per agent</h3>
        <div className="grid gap-2 sm:grid-cols-2">
          {perAgent.map(({ agent, ms }) => (
            <div key={agent.key} className="rounded-xl border border-[var(--border)] bg-white/[0.02] px-3 py-2.5">
              <div className="flex items-center justify-between text-[12px]">
                <span className="font-medium" style={{ color: agent.color }}>
                  {agent.label}
                </span>
                <span className="font-mono text-[11px] text-[var(--text-dim)]">
                  {formatDuration(ms)} · {Math.round((ms / total) * 100)}%
                </span>
              </div>
              <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[0.05]">
                <div className="grow-x h-full rounded-full" style={{ width: `${(ms / slowest) * 100}%`, background: agent.color }} />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function CriticTab({ result }: { result: ReportResult }) {
  const { verdict, feedback, unsupported_claims } = result.critic;
  const passed = result.status === "passed";
  return (
    <div className="flex flex-col gap-4 p-4 sm:p-5">
      <div className="flex items-center gap-3">
        <span
          className="flex h-10 w-10 items-center justify-center rounded-xl"
          style={{ background: passed ? "#34d3991f" : "#fbbf241f", color: passed ? "var(--ok)" : "var(--warn)" }}
        >
          {passed ? <ShieldCheck size={18} /> : <ShieldAlert size={18} />}
        </span>
        <div>
          <div className="text-[11px] uppercase tracking-wide text-[var(--text-faint)]">Final verdict</div>
          <div className="text-sm font-semibold capitalize">{verdict ?? (passed ? "pass" : "revise")}</div>
        </div>
      </div>
      {feedback && (
        <div className="rounded-xl border border-[var(--border)] bg-white/[0.02] px-4 py-3">
          <div className="mb-1 text-[11px] font-medium uppercase tracking-wide text-[var(--text-faint)]">Feedback</div>
          <p className="whitespace-pre-wrap text-[13px] leading-relaxed text-[var(--text-dim)]">{feedback}</p>
        </div>
      )}
      <div>
        <div className="mb-2 text-[11px] font-medium uppercase tracking-wide text-[var(--text-faint)]">
          Flagged claims ({unsupported_claims?.length ?? 0})
        </div>
        {unsupported_claims?.length ? (
          <ul className="flex flex-col gap-1.5">
            {unsupported_claims.map((c, i) => (
              <li key={i} className="flex gap-2 rounded-xl border border-[#fbbf2433] bg-[#fbbf240a] px-3 py-2 text-[13px] text-[var(--text-dim)]">
                <ShieldAlert size={14} className="mt-0.5 shrink-0 text-[var(--warn)]" />
                {c}
              </li>
            ))}
          </ul>
        ) : (
          <p className="flex items-center gap-2 text-[13px] text-[var(--text-dim)]">
            <Check size={14} className="text-[var(--ok)]" /> No unsupported claims. Every sentence is backed by evidence.
          </p>
        )}
      </div>
    </div>
  );
}

function Empty({ text }: { text: string }) {
  return <p className="px-5 py-10 text-center text-sm text-[var(--text-faint)]">{text}</p>;
}
